apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nba-ingress
spec:
  rules:
    - host: nba-ai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nba-backend-service
                port:
                  number: 80
